
(function(root){
'use strict';
// Offline, read-only liquidity views. The data modules own the calculations.
const F=root.ReviewFinancial,T=root.ReviewTreasury;
if(!F||typeof F.page!=='function')throw Error('ReviewTreasuryUI requires the monthly page.');
const originalPage=F.page,finite=Number.isFinite,nf=new Intl.NumberFormat('ja-JP',{maximumFractionDigits:20});
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>finite(v)?nf.format(v===0?0:v):'—';
const sumKnown=xs=>{if(!xs.length||!xs.every(Number.isSafeInteger))return null;const total=xs.reduce((n,v)=>n+BigInt(v),0n),limit=BigInt(Number.MAX_SAFE_INTEGER);return total>=-limit&&total<=limit?Number(total):null;};
const unique=xs=>[...new Set(xs.filter(v=>v!==null&&v!==undefined&&String(v).trim()!==''))];
const reason=v=>typeof v==='string'?v: v?.reason||v?.text||v?.label||'';
const notes=xs=>(xs||[]).map(reason).filter(Boolean);
const state=s=>s==='agree'?'一致（読込範囲）':s==='difference'?'差額あり':s==='reference'?'参考集計':s==='report'?'資料の残高':s==='rollforward'?'期首＋仕訳': '確認待ち';
const badge=s=>`<span class="badge ${s==='difference'?'red':s==='pending'||s==='unknown'?'warn':''}">${esc(state(s))}</span>`;
const money=(v,extra='')=>`<span class="ts-money${finite(v)&&v<0?' ts-negative':''}">${num(v)}${extra}</span>`;
function rowList(rows){
 const seen=new Set();return (rows||[]).filter(r=>{const id=JSON.stringify([r.source,r.line,r.date,r.journalId||r.id,r.account,r.tagDimension,r.tagValue]);if(seen.has(id))return false;seen.add(id);return true;});
}
function sourceRefs(rows){return unique(rowList(rows).map(r=>`${r.source||'元CSV名未保存'}${r.line?' '+r.line+'行':''}${r.journalId||r.id?'（仕訳 '+(r.journalId||r.id)+'）':''}`));}
function evidenceHTML(rows){
 const rs=rowList(rows);if(!rs.length)return '<p class="small">対応する元CSVの行は未確定です。</p>';
 return `<details class="ts-evidence"><summary>根拠の仕訳・元CSV（${rs.length}行）</summary><div class="tablewrap"><table class="datatable"><thead><tr><th scope="col">日付・仕訳番号</th><th scope="col">借方／帳票科目</th><th scope="col" class="num">金額（円）</th><th scope="col">貸方</th><th scope="col" class="num">金額（円）</th><th scope="col">摘要・元CSV</th></tr></thead><tbody>${rs.map(r=>`<tr><td>${esc(r.date||'未確定')}<br>${esc(r.journalId||r.id||'')}</td><td>${esc(r.debit||r.account||'')}</td><td class="num">${money(r.debit?r.debitAmount:r.amount)}</td><td>${esc(r.credit||'')}</td><td class="num">${r.credit?money(r.creditAmount):'—'}</td><td>${esc(r.description||r.tagValue||'')}<p class="small">${esc(r.source||'元CSV名未保存')}${r.line?' '+num(r.line)+'行':''}</p></td></tr>`).join('')}</tbody></table></div></details>`;
}
function sourceNotes(session,treasury,settlement){
 const missing=[];if(!(session.datasets?.priorPL||[]).length)missing.push('前期PLが未読込です。前年の同じ期間の利益・科目比較は確認待ちです。');
 if(!(session.datasets?.priorBS||[]).length)missing.push('前期BSが未読込です。前期末と当期首の連続性、前年同月の残高比較は確認待ちです。');
 const all=unique([...missing,...notes(treasury?.notes),...notes(settlement?.notes)]);
 return all.length?`${missing.length?`<div class="notice ts-source-summary">${missing.map(x=>`<p>${esc(x)}</p>`).join('')}</div>`:''}<details class="ts-details ts-source-notes"><summary>資料の不足・計算の前提（${all.length}件）</summary><ul>${all.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></details>`:'';
}
function continuityHTML(treasury){
 const all=treasury?.continuity||[],diff=all.filter(c=>c.status==='difference').length,pending=all.filter(c=>c.status==='pending').length;
 const openings=all.filter(c=>c.kind!=='profit-bridge'),bridges=all.filter(c=>c.kind==='profit-bridge');
 const rows=list=>list.map(c=>`<tr><th scope="row">${esc(c.label||c.account||'損益の年度対応')}${c.tagDimension?`<p class="small">${esc(c.tagValue||'未選択')}</p>`:''}</th><td>${esc(c.openingMonth||'未確定')}</td><td class="num">${money(c.prior)}</td><td class="num">${money(c.current)}</td><td class="num">${money(c.difference)}</td><td>${badge(c.status)}<p class="small">${esc(c.reason||notes(c.reasons).join(' '))}</p>${c.basis?`<p class="small">計算根拠：${esc(c.basis)}</p>`:''}${evidenceHTML(c.rows)}</td></tr>`).join('');
 const table=(list,bridge)=>`<div class="tablewrap"><table class="datatable">${bridge?'<caption>個人事業の利益・事業主勘定から元入金をつなぐ</caption>':''}<thead><tr><th scope="col">科目・内訳</th><th scope="col">期首月</th><th scope="col" class="num">${bridge?'前期末の各勘定から計算した元入金':'前期末'}（円）</th><th scope="col" class="num">${bridge?'当期首の元入金':'当期首'}（円）</th><th scope="col" class="num">当期−前期（円）</th><th scope="col">状態・理由・根拠</th></tr></thead><tbody>${rows(list)}</tbody></table></div>`;
 return `<details class="ts-details ts-continuity"${diff?' open':''}><summary>前期末 → 当期首の連続性（差額 ${diff}件・確認待ち ${pending}件）</summary><p class="small">同じ科目・内訳・年度の残高を比較します。個人事業の期首振替は、振替の前／後をそろえて確認します。</p>${openings.length?table(openings,false):'<p>前期BSと当期BSの期首を読み込むと比較できます。</p>'}${bridges.length?table(bridges,true):''}</details>`;
}
function priorComparisonHTML(treasury){
 const p=treasury?.priorComparison||{},pl=p.summary?.pl?.length?p.summary.pl:p.pl||[],bsAll=p.summary?.bs?.length?p.summary.bs:p.bs||[];
 const bsMonth=unique(bsAll.filter(c=>finite(c.current)).map(c=>c.month)).sort().at(-1),bs=p.summary?.bs?.length?bsAll:bsAll.filter(c=>c.month===bsMonth);
 const table=(list,kind)=>list.length?`<div class="tablewrap"><table class="datatable"><caption>${kind==='PL'?'前年と同じ期間のPL比較':'前年同月のBS比較'+(bsMonth?'（'+esc(bsMonth)+'）':'')}</caption><thead><tr><th scope="col">科目</th><th scope="col" class="num">前期（円）</th><th scope="col" class="num">当期（円）</th><th scope="col" class="num">当期−前期（円）</th><th scope="col">状態・期間・根拠</th></tr></thead><tbody>${list.map(c=>`<tr><th scope="row">${esc(c.account||c.label||'')}</th><td class="num">${money(c.prior)}</td><td class="num">${money(c.current)}</td><td class="num">${money(c.difference)}</td><td>${badge(c.status)}<p class="small">${esc(c.reason||notes(c.reasons).join(' '))}${c.month?' 当期 '+esc(c.month)+(c.priorMonth?'／前期 '+esc(c.priorMonth):''):''}</p>${evidenceHTML(c.rows)}</td></tr>`).join('')}</tbody></table></div>`:`<p class="small">${kind==='PL'?'前期PL':'前期BS'}と対応する当期帳票がそろうと表示します。</p>`;
 return `<details class="ts-details ts-prior-comparison"><summary>前年と同じ期間の利益・残高を比べる</summary>${p.period?`<p class="small">当期 ${esc(p.period.start||'未確定')}〜${esc(p.period.end||'未確定')} ／ 前期 ${esc(p.period.priorStart||'未確定')}〜${esc(p.period.priorEnd||'未確定')}</p>`:''}${table(pl,'PL')}${table(bs,'BS')}</details>`;
}
const CF_FIELDS=[['profit','単月利益'],['nonCash','非資金損益の調整'],['workingCapital','売掛・買掛等の増減調整'],['operating','営業の資金増減（参考）'],['investing','投資の資金増減（候補）'],['financing','借入・事業主等の資金増減（候補）'],['classifiedChange','上記分類の合計'],['cashChange','現預金残高の実際の増減'],['residual','分類で説明できない差']];
function cashflowHTML(treasury){
 const ms=treasury?.monthly||[],period=treasury?.period||{},observed=treasury?.observedPeriod,aggregates=[];
 if(observed?.start&&observed?.end&&(observed.start!==period.start||observed.end!==period.end))aggregates.push({label:'読込範囲の合計',data:observed});
 aggregates.push({label:'設定対象期間の合計',data:period});
 const totalCells=key=>aggregates.map(a=>`<td class="num">${money(a.data[key])}</td>`).join('');
 return `<details class="ts-details ts-cashflow"><summary>利益と現預金をつなぐ月別の資金移動（参考）</summary><p class="small">利益に非資金損益と運転資金の増減を加え、投資・借入等の仕訳候補と現預金増減を照合します。分類候補と未説明の差を残して確認する集計です。</p>${ms.length?`<div class="tablewrap"><table class="datatable ts-cashflow-table"><thead><tr><th scope="col">項目（円）</th>${ms.map(m=>`<th scope="col" class="num">${esc(m.month)}</th>`).join('')}${aggregates.map(a=>`<th scope="col" class="num">${esc(a.label)}<br><span class="small">${esc(a.data.start||'未確定')}〜${esc(a.data.end||'未確定')}</span></th>`).join('')}</tr></thead><tbody>${CF_FIELDS.map(([key,label])=>`<tr${['operating','classifiedChange','cashChange','residual'].includes(key)?' class="ts-subtotal"':''}><th scope="row">${esc(label)}</th>${ms.map(m=>`<td class="num">${money(m[key])}</td>`).join('')}${totalCells(key)}</tr>`).join('')}<tr><th scope="row">月初現預金</th>${ms.map(m=>`<td class="num">${money(m.openingCash)}</td>`).join('')}${totalCells('openingCash')}</tr><tr><th scope="row">月末現預金</th>${ms.map(m=>`<td class="num">${money(m.closingCash)}</td>`).join('')}${totalCells('closingCash')}</tr><tr><th scope="row">資料・分類の条件</th>${ms.map(m=>`<td>${badge(m.status)}</td>`).join('')}${aggregates.map(a=>`<td>${badge(a.data.status)}</td>`).join('')}</tr></tbody></table></div>${aggregates.map(a=>`<p class="small">${esc(a.label)}の前提：${esc(notes(a.data.reasons).join(' ')||'読込範囲内の参考集計です。')}</p>`).join('')}<div class="ts-month-evidence">${ms.map(m=>`<details class="ts-details"><summary>${esc(m.month)} ${state(m.status)}${finite(m.residual)&&m.residual!==0?' ／ 未説明の差 '+num(m.residual)+'円':''}</summary><p class="small">${esc(notes(m.reasons).join(' '))}</p>${m.profitSource?`<p class="small">利益の基準：${esc(reason(m.profitSource)||m.profitSource)}</p>`:''}${m.lines?.length?`<div class="tablewrap"><table class="datatable"><thead><tr><th scope="col">分類・科目</th><th scope="col" class="num">金額（円）</th><th scope="col">状態・根拠</th></tr></thead><tbody>${m.lines.map(l=>`<tr><th scope="row">${esc(l.label||l.kind)}${l.account?' ／ '+esc(l.account):''}</th><td class="num">${money(l.amount)}</td><td>${badge(l.status||m.status)}<p class="small">${esc(notes(l.reasons).join(' '))}</p>${evidenceHTML(l.rows)}</td></tr>`).join('')}</tbody></table></div>`:''}${m.direct?`<p class="small">現預金を含む仕訳からの直接集計候補：営業 ${num(m.direct.operating)}円 ／ 投資 ${num(m.direct.investing)}円 ／ 借入・事業主等 ${num(m.direct.financing)}円 ／ 未分類 ${num(m.direct.unallocated)}円。複合仕訳の配分が不明なものは未分類に残します。</p>`:''}${evidenceHTML(m.rows)}</details>`).join('')}</div>`:'<p>当期BS・PL・仕訳帳を読み込むと参考集計を表示します。</p>'}</details>`;
}
function eventsHTML(p){
 const all=[...(p.events||[]),...(p.nonCashEvents||[])].sort((a,b)=>String(b.date).localeCompare(String(a.date)));
 return `<details class="ts-evidence ts-events"><summary>入出金・相殺等の候補を日付順に確認（${all.length}件）</summary><p class="small">対象科目の減少と、同じ仕訳全体の現預金の純増減（入金＋・出金−）を表示します。複合仕訳の現預金額を取引先に配分した結果ではありません。</p>${all.length?`<div class="tablewrap"><table class="datatable"><thead><tr><th scope="col">日付</th><th scope="col">候補の種類</th><th scope="col" class="num">対象科目の減少（円）</th><th scope="col" class="num">仕訳全体の現預金純増減（円）</th><th scope="col">根拠</th></tr></thead><tbody>${all.map(e=>`<tr><td>${esc(e.date)}<p class="small">${e.current?'当期':'前期'}</p></td><td>${e.classification==='cash_linked'?'現預金を伴う決済候補':e.classification==='cancellation'?'取消・返金候補':'振替・相殺等の候補'}</td><td class="num">${money(e.amount)}</td><td class="num">${money(e.actualCashNet)}</td><td>${evidenceHTML(e.rows)}</td></tr>`).join('')}</tbody></table></div>`:'<p class="small">観測できた減少・決済候補はありません。</p>'}</details>`;
}
function cycleHTML(parties){
 return `<details class="ts-details ts-cycles"><summary>仕訳から見える回収・支払の間隔（${parties.length}先）</summary><p class="small">現預金を伴う決済候補の計上日から、観測できた日数の中央値とばらつきを示します。請求書の消込・約定期日・延滞日数は、この間隔から確定できません。</p>${parties.length?`<div class="tablewrap"><table class="datatable"><thead><tr><th scope="col">科目・取引先</th><th scope="col" class="num">候補日の数</th><th scope="col" class="num">間隔の中央値</th><th scope="col">最後の候補日</th><th scope="col">傾向・確認事項・仕訳</th></tr></thead><tbody>${parties.map(p=>{const i=p.interval||{};return `<tr><th scope="row">${esc(p.account)}<p class="small">${esc(p.label||p.party||'未選択')}</p></th><td class="num">${num(i.dateCount)}日</td><td class="num">${num(i.median)}日<p class="small">間隔の幅 ${num(i.spread)}日</p></td><td>${esc(i.lastDate||'未観測')}${finite(i.daysSinceLast)?`<p class="small">集計基準日まで ${num(i.daysSinceLast)}日</p>`:''}</td><td><span class="badge ${i.regularity==='insufficient'?'warn':''}">${i.regularity==='regular'?'間隔が比較的そろう':i.regularity==='variable'?'間隔にばらつき':'観測数不足'}</span>${finite(i.dayOfMonth?.median)?`<p class="small">月内の日付：中央値 ${num(i.dayOfMonth.median)}日（幅 ${num(i.dayOfMonth.spread)}日）</p>`:''}<p class="small">${esc(notes(p.reviewReasons).join(' '))}</p>${eventsHTML(p)}</td></tr>`;}).join('')}</tbody></table></div>`:'<p>取引先付きの回収・支払候補を読み込むと表示します。</p>'}</details>`;
}
function settlementsHTML(settlement){
 if(!settlement)return '<div class="notice">売掛・買掛・未払の残高と決済候補を計算する資料が未読込です。</div>';
 const parties=settlement.parties||[],accounts=(settlement.accounts||[]).map(a=>{
  if(!a.analysisAsOf)return {...a,viewAsOf:a.asOf};
  const ps=parties.filter(p=>p.account===a.account).map(p=>({...p,closing:p.analysisClosing,closingBasis:p.analysisClosingBasis||'reference'})),known=ps.filter(p=>finite(p.closing)),unknown=ps.filter(p=>!finite(p.closing));
  return {...a,viewAsOf:a.analysisClosingAsOf||a.analysisAsOf,configuredClosing:a.totalClosing,totalClosing:a.analysisClosingTotal,knownParties:known,unknownParties:unknown,knownClosingTotal:sumKnown(known.map(p=>p.closing)),unallocatedClosing:a.analysisUnallocatedClosing};
 });
 const knownHTML=a=>a.knownParties?.length?`<div class="tablewrap"><table class="datatable"><thead><tr><th scope="col">取引先</th><th scope="col" class="num">期首（円）</th><th scope="col" class="num">確認できる残高（円）</th><th scope="col">基準・確認事項</th></tr></thead><tbody>${a.knownParties.map(p=>`<tr><th scope="row">${esc(p.label||p.party||'未選択')}</th><td class="num">${money(p.opening)}${!finite(p.opening)?'<p class="small">期首未確定</p>':''}</td><td class="num">${money(p.closing)}</td><td>${badge(p.closingBasis)}<p class="small">${esc(notes(p.reviewReasons).join(' '))}</p>${evidenceHTML(p.rows)}</td></tr>`).join('')}</tbody></table></div>`:'<p class="small">この科目では取引先別の残高を確定できません。前期BSの取引先内訳または当期BSの取引先別期首があると、仕訳とつないで確認できます。過去の仕訳帳からの参考推計は「取引先別の残高と回収・支払の状況」で確認できます。</p>';
 const unknownHTML=a=>a.unknownParties?.length?`<details class="ts-evidence"><summary>残高未確定の取引先（${a.unknownParties.length}先）</summary><div class="tablewrap"><table class="datatable"><thead><tr><th scope="col">取引先</th><th scope="col">残高</th><th scope="col" class="num">読込範囲の累計増減（円）</th><th scope="col">確認事項</th></tr></thead><tbody>${a.unknownParties.map(p=>`<tr><th scope="row">${esc(p.label||p.party||'未選択')}</th><td>—（${finite(p.opening)?'読込条件未確定':'期首未確定'}）</td><td class="num">${money(p.change)}<p class="small">${p.changeThrough?esc(p.changeThrough)+'まで':''}</p></td><td><p class="small">${esc(notes(p.reviewReasons).join(' ')||'取引先別の期首・前期末残高を確認します。')}</p>${evidenceHTML(p.rows)}</td></tr>`).join('')}</tbody></table></div></details>`:'';
 return `<details class="ts-details ts-settlements" open><summary>売掛・買掛・未払の残りと取引先別の内訳</summary><p class="small">読込済み仕訳の観測末時点のBS・取引先残高を表示します。取引先別の期首や残高を確定できない場合は — とし、累計増減と区別します。</p>${accounts.length?`<div class="tablewrap"><table class="datatable"><thead><tr><th scope="col">科目・基準日</th><th scope="col" class="num">科目全体の期首（円）</th><th scope="col" class="num">科目全体の残高（円）</th><th scope="col" class="num">確認できる取引先残高合計（円）</th><th scope="col">未確定・詳細</th></tr></thead><tbody>${accounts.map(a=>`<tr><th scope="row">${esc(a.account)}<p class="small">${a.direction==='receipt'?'回収を確認':'支払を確認'} ／ ${esc(a.viewAsOf||'基準日未確定')}</p></th><td class="num">${money(a.totalOpening)}</td><td class="num">${money(a.totalClosing)}</td><td class="num">${money(a.knownClosingTotal)}</td><td><p class="small">残高を確認できる取引先 ${(a.knownParties||[]).length}先 ／ 残高未確定 ${(a.unknownParties||[]).length}先。内訳未配賦の期首 ${num(a.unallocatedOpening)}円、残高 ${num(a.unallocatedClosing)}円。</p><details class="ts-evidence"><summary>取引先残高と元資料を確認</summary>${knownHTML(a)}${unknownHTML(a)}${a.configuredClosing!==undefined&&a.asOf!==a.viewAsOf?`<p class="small">設定末日 ${esc(a.asOf||settlement.scopeEnd||'未確定')} の科目帳票残高 ${num(a.configuredClosing)}円。観測末日の残高とは分けて確認します。</p>`:''}${evidenceHTML(a.rows)}</details></td></tr>`).join('')}</tbody></table></div>`:'<p>対象科目のBSと仕訳帳を読み込むと確認できます。</p>'}</details>${cycleHTML(parties)}`;
}
function alertsHTML(settlement){
 const alerts=settlement?.alerts||[];return alerts.length?`<details class="ts-details ts-alerts"><summary>回収・支払について先に確認すること（${alerts.length}件）</summary><div class="ts-alertlist">${alerts.map(a=>`<article><strong>${esc(a.title||a.kind)}</strong>${a.account||a.party?`<span class="small">${esc(a.account||'')} ${esc(a.party||'')}</span>`:''}<p>${esc(a.reason||'元資料の残高・決済候補を確認します。')}</p>${finite(a.amount)?`<span class="small">確認する金額 ${money(a.amount)}円</span>`:''}${evidenceHTML(a.rows)}</article>`).join('')}</div></details>`:'';
}
function panel(session,model){
 const treasury=model.treasury||T?.build(session,model),settlement=model.settlement,liquidity=settlement?.liquidity||{},snapshotMonth=liquidity.asOf?.slice(0,7),sameMonth=treasury?.liquidity?.monthly?.find(m=>m.month===snapshotMonth),ar=sameMonth?.receivables??null,ap=liquidity.outstandingPayables,period=treasury?.period||{},snapshotLabel=liquidity.asOf?'（'+esc(liquidity.asOf)+(/^\d{4}-\d{2}-\d{2}$/.test(liquidity.asOf)?'時点':'末')+'）':'';
 const operatingPeriod=treasury?.observedPeriod?.start&&treasury.observedPeriod.end?treasury.observedPeriod:period;
 return `<section class="panel monthly-panel treasury-panel" id="treasuryReview" aria-labelledby="treasuryReviewTitle"><div class="panelhead"><div><h2 id="treasuryReviewTitle">資金の動きと、回収・支払の残り</h2><span class="small">対象 ${esc(session.project.start)}〜${esc(session.project.end)} ／ 金額は円。—は確定できない金額です。</span></div><div class="ts-actions"><button class="btn small" data-action="import" data-type="priorPL">前期PLを読込</button><button class="btn small" data-action="import" data-type="priorBS">前期BSを読込</button><button class="btn small" data-treasury-export="1">資金確認CSV</button></div></div><div class="panelbody"><div class="ts-overview"><div><span>現預金${snapshotLabel}</span><strong>${money(liquidity.cash)}<small> 円</small></strong></div><div><span>売掛・未収の残高${snapshotLabel}</span><strong>${money(ar)}<small> 円</small></strong></div><div><span>買掛・未払の残高${snapshotLabel}</span><strong>${money(ap)}<small> 円</small></strong></div><div><span>営業の資金増減（${esc(operatingPeriod.start||'未確定')}〜${esc(operatingPeriod.end||'未確定')}・参考）</span><strong>${money(operatingPeriod.operating)}<small> 円</small></strong>${badge(operatingPeriod.status)}</div></div>${finite(liquidity.netAfterPayables)&&liquidity.ready?`<p class="small">買掛・未払残高を現預金から差し引いた参考額 ${money(liquidity.netAfterPayables)}円。実際の支払期日や入金予定は別途確認します。</p>`:''}${notes(liquidity.notes).length?`<p class="small">${esc(notes(liquidity.notes).join(' '))}</p>`:''}${sourceNotes(session,treasury,settlement)}${alertsHTML(settlement)}${settlementsHTML(settlement)}${cashflowHTML(treasury)}${continuityHTML(treasury)}${priorComparisonHTML(treasury)}${treasury?.scope?`<p class="small ts-scope">${esc(reason(treasury.scope)||treasury.scope)}</p>`:''}</div></section>`;
}
function csv(model){
 const q=v=>{if(finite(v))return String(v);const s=v===null||v===undefined?'':String(v),safe=/^[=+\-@\t\r]/.test(s)?"'"+s:s;return '"'+safe.replace(/"/g,'""')+'"';},rows=[['区分','月・期間','科目・取引先','項目','金額・日数','基準・状態','理由','元CSV・仕訳番号・行番号']];
 const treasury=model.treasury||{},settlement=model.settlement||{};
 for(const m of treasury.monthly||[])for(const [key,label]of CF_FIELDS)rows.push(['月別資金移動',m.month,'',label,m[key],state(m.status),notes(m.reasons).join(' '),sourceRefs(m.rows).join('／')]);
 if(treasury.period)for(const [key,label]of CF_FIELDS)rows.push(['期間資金移動',[treasury.period.start,treasury.period.end].filter(Boolean).join('〜'),'',label,treasury.period[key],state(treasury.period.status),notes(treasury.period.reasons).join(' '),sourceRefs(treasury.period.rows).join('／')]);
 if(treasury.observedPeriod)for(const [key,label]of CF_FIELDS)rows.push(['観測範囲の資金移動',[treasury.observedPeriod.start,treasury.observedPeriod.end].filter(Boolean).join('〜'),'',label,treasury.observedPeriod[key],state(treasury.observedPeriod.status),notes(treasury.observedPeriod.reasons).join(' '),sourceRefs(treasury.observedPeriod.rows).join('／')]);
 for(const c of treasury.continuity||[]){for(const [key,label]of [['prior','前期末'],['current','当期首'],['difference','当期−前期']])rows.push(['期首連続性',c.openingMonth||'',[c.account,c.tagValue].filter(Boolean).join('／'),label,c[key],state(c.status),c.reason||notes(c.reasons).join(' '),sourceRefs(c.rows).join('／')]);}
 for(const kind of ['pl','bs'])for(const c of treasury.priorComparison?.[kind]||[])for(const [key,label]of [['prior','前年同月'],['current','当月'],['difference','当期−前期']])rows.push(['前期'+kind.toUpperCase()+'比較',c.month||'',c.account||'',label,c[key],state(c.status),c.reason||notes(c.reasons).join(' '),sourceRefs(c.rows).join('／')]);
 for(const a of settlement.accounts||[]){
  rows.push(['売掛・買掛・未払残高',a.asOf||settlement.scopeEnd||'',a.account,'設定末日のBS科目残高',a.totalClosing,'科目合計','観測末日とは別の基準日です。',sourceRefs(a.rows).join('／')]);
  rows.push(['売掛・買掛・未払残高',a.analysisClosingAsOf||a.analysisAsOf||settlement.analysisThrough||'',a.account,'観測末月のBS科目残高',a.analysisClosingTotal,'科目合計','当期仕訳の観測末月に対応する帳票残高です。',sourceRefs(a.analysisRows||a.rows).join('／')]);
 }
 for(const p of settlement.parties||[]){
  const party=[p.account,p.label||p.party].join('／'),why=notes(p.reviewReasons).join(' ');
  rows.push(['取引先残高',p.openingDate||'',party,'取引先期首',p.opening,state(p.openingSource),why,sourceRefs(p.rows).join('／')]);
  rows.push(['取引先残高',p.asOf||settlement.scopeEnd||'',party,'設定末日の取引先残高',p.closing,state(p.closingBasis),why,sourceRefs(p.rows).join('／')]);
  rows.push(['取引先残高',p.analysisClosingAsOf||p.analysisThrough||settlement.analysisThrough||'',party,'観測末月の取引先残高',p.analysisClosing,state(p.analysisClosingBasis),why,sourceRefs(p.analysisRows||p.rows).join('／')]);
  rows.push(['取引先増減',p.changeThrough||settlement.analysisThrough||'',party,'読込範囲の累計増減',p.change,'残高とは区別する',why,sourceRefs(p.rows).join('／')]);
  rows.push(['取引先増減',p.asOf||settlement.scopeEnd||'',party,'設定対象期間の累計増減',p.periodChange,'未読込月があれば未確定',why,sourceRefs(p.rows).join('／')]);
  rows.push(['観測した決済間隔','',party,'間隔の中央値（日）',p.interval?.median,'現預金を伴う候補の計上日','請求書消込・約定期日・延滞日数は未確定',sourceRefs((p.events||[]).flatMap(e=>e.rows||[])).join('／')]);
  for(const e of [...(p.events||[]),...(p.nonCashEvents||[])])for(const [key,label]of [['amount','対象科目の減少'],['actualCashAmount','同じ仕訳全体の入出金額'],['actualCashNet','同じ仕訳全体の現預金純増減']])rows.push(['決済候補',e.date,party,label,e[key],e.classification,'複合仕訳の現預金額を取引先に配分した結果ではありません。',sourceRefs(e.rows).join('／')]);
 }
 for(const a of settlement.alerts||[])rows.push(['回収・支払の確認','',[a.account,a.party].filter(Boolean).join('／'),a.title||a.kind,a.amount,'確認候補',a.reason||'',sourceRefs(a.rows).join('／')]);
 return '\uFEFF'+rows.map(row=>row.map(q).join(',')).join('\r\n');
}
let current=null;
F.page=function(session,result,focus){
 const html=originalPage.call(this,session,result,focus),model=result?.financial;current=model?{session,model}:null;if(!model)return html;
 const add=panel(session,model),marker='<section class="panel monthly-panel" id="vtChanges"',at=html.indexOf(marker);
 if(at>=0)return html.slice(0,at)+add+html.slice(at);
 const audit=html.indexOf('id="auditIntegrity"'),afterAudit=audit<0?-1:html.indexOf('</section>',audit);
 return afterAudit<0?html+add:html.slice(0,afterAudit+10)+add+html.slice(afterAudit+10);
};
if(typeof document!=='undefined')document.addEventListener('click',e=>{
 const b=e.target.closest?.('[data-treasury-export]');if(!b||!current)return;
 const blob=new Blob([csv(current.model)],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='資金確認_'+current.session.project.start+'_'+current.session.project.end+'.csv';document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);
});
root.ReviewTreasuryUI={panel,csv,evidenceHTML,version:1};
})(typeof window!=='undefined'?window:globalThis);
